### ISSUE TITLE
DatePicker 日期选择器在form表单中初始化后值未被格式化

### ISSUE THREAD

**Issue by WittBulter** [ElemeFE/element-angular#1]
Issue Type:
- [x] Bug

Version & Environment:  

Description:

`<el-date-picker  [formControlName]="date" size="small" [format]="'yyyy-mm-dd'"></el-date-picker>`

formGroup初始化后date有值1970-09-01 12:00:00，然而[format]="'yyyy-mm-dd'"并没有生效。
@Cyclone77

**Comment by WittBulter** [comment]
`format` 的月份标识应为 `MM` 而不是 `mm`。
但组件上月份的变化上有一些问题，#2

**Comment by Cyclone77** [comment]
嗯 不过mm angular的管道也是格式化完也是 1970-00-01，控件的问题依然存在

**Comment by Cyclone77** [comment]
@WittBulter 或许是我没表述清楚，是在设置`el-date-picker`值的时候并没有执行格式化。

**Comment by WittBulter** [comment]
设置值的时候不会格式化，只有回调时才会格式化
