### ISSUE TITLE
upload组件使用上传为空

### ISSUE THREAD

**Issue by Wait14** [ElemeFE/element-angular#103]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  
最新版"element-angular": "^0.7.4",

Description:
按照文档使用了照片墙,下图的action是自己的后台接口地址
html：
`<el-upload action="/io/to-upyun"
                       name="boss"
                       accept="image/*"
                       list-type="picture-card"
                       (change)="changeHandle($event)"
                       (preview)="previewHandle($event)"
                       (remove)="removeHandle($event)">
                <ng-template #trigger>
                    <i class="el-icon-plus"></i>
                </ng-template>
            </el-upload>

            <el-dialog [(visible)]="showDialog" size="tiny">
                <img width="100%" [src]="dialogImageUrl" alt="">
            </el-dialog>`
ts:
`import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-game-list',
  templateUrl: './game-list.component.html',
  styleUrls: ['./game-list.component.scss']
})
export class GameListComponent implements OnInit {
    showDialog:any;
    dialogImageUrl:any;
    imageUrl:any;

  constructor() { }

  ngOnInit() {
  }
    previewHandle($event){}
    removeHandle($event){}
    successHandle(file: any): void {
    
    }
    changeHandle($event){
        console.log($event);
    }

    errorHandle(err: any): void {

    }

}
`
但是照片上传后，发起了两次请求 一次option 一次post
changeHandle 里啥都没有，两次请求没传东西

![1524620254](https://user-images.githubusercontent.com/25865076/39221925-54addeee-486c-11e8-999d-fe6e5a221ca1.png)
![image](https://user-images.githubusercontent.com/25865076/39222052-0f828332-486d-11e8-9eab-b27a274cb3b2.png)

**Comment by WittBulter** [comment]
麻烦你调整一下代码排版格式或者提供一个在线 IDE 的复现代码。

**Comment by Wait14** [comment]
谢谢回复，项目赶工，目前已经用其它方案代替upload组件，回头再在相同环境下复现，有问题了再发过来。另外你们有没有民间的交流群 组织啥的.....
@WittBulter 
谢谢

**Comment by WittBulter** [comment]
我的微信是 WittBulter，有一个微信群，我可以拉你一起讨论。@Wait14
