### ISSUE TITLE
table 有点击行事件么?  点击事件怎么使用?给个dome好么?

### ISSUE THREAD

**Issue by gaomingen** [ElemeFE/element-angular#106]
Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

Version & Environment:  

0.7.0

Description:

如题,  换了好几种写法没有都生效 , 帮写个dome呗 ,谢谢.

**Comment by WittBulter** [comment]
你好，没有点击行的事件，但是有点击单元格触发的事件： `cell-click`。
