### ISSUE TITLE
[Feature]对element-angular开发者的一些建议

### ISSUE THREAD

**Issue by icepoint0** [ElemeFE/element-angular#109]
1.建议先升级至angular v6
2.dev工具还是自己编写的gulp？建议改为官方钦定的angular-cli 
3.element-ui 还有个peer dependency 是 vue的？
4.多个组件中多种实现方式相当粗糙，充斥着一股浓浓的vue 风格。。。dropdown 。等等。
5.如果作者采纳我这些建议可以把我列入contributor。个人对angular相关库都比较感兴趣。暂时不打算做pr，感觉如果做了都是破坏性升级。从依赖到构筑。

**Comment by WittBulter** [comment]
会尽快升级。
另外风格和依赖都是因为从 Element 繁衍而来，所以组件本身是继承 Element UI 的 style，整体 API 也进肯呢过的保持与 Element 风格相似。

谢谢你的支持，如果你有改进也可以提 PR。
