### ISSUE TITLE
tree-bug

### ISSUE THREAD

**Issue by shiyuanping** [ElemeFE/element-angular#11]
Issue Type:
- [ ] Bug

Version & Environment:  
0.56

Description:
树组件的例子-<默认展开和默认选中>，运行后没有展开效果。
经过多次测试，需将expanded: true添加到每个层级，望能修复这个错误例子

**Comment by WittBulter** [comment]
默认展开: `[default-expanded-keys]="['1.1.1', '2.1.1']` ，数组中的每一项表示 id。
同理：`[default-checked-keys]="['1.1.1', '2.1.1']"`。
如果要设置默认展开与选中，必须要为数据中的每一项增加 id，展开与选中的数组中填入这些 id。我后面会在文档中加入这个提示。
