### ISSUE TITLE
分页组件 当总数为0时候  为什么还会显示很多页面 并显示所有配置项

### ISSUE THREAD

**Issue by Yin-Xie** [ElemeFE/element-angular#110]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  

分页组件 当总数为0时候  为什么还会显示很多页面 并显示所有配置项

Description:
![image](https://user-images.githubusercontent.com/24772971/40095870-cd9c7f64-5900-11e8-9a58-5c1665845497.png)

**Comment by icepoint0** [comment]
这个项目写的挺烂的。。还是用zorro吧 哥们

**Comment by WittBulter** [comment]
fixed, waiting release.

**Comment by WittBulter** [comment]
v0.7.6 released.
