### ISSUE TITLE
如何更改input的宽度

### ISSUE THREAD

**Issue by Cyclone77** [ElemeFE/element-angular#12]
Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

Version & Environment:  

![123](https://user-images.githubusercontent.com/10395760/35726615-76a71d1a-0840-11e8-80cb-c099ff8b3960.png)

Description:

如何 更改textarea宽度，在设置表单为[inline]="true" 一行内。

**Comment by WittBulter** [comment]
你可以通过 [el-class](https://element-angular.faas.ele.me/guide/directives) 指令更改任何组件的样式。
覆盖样式时，注意 `ViewEncapsulation` 的方式。
