### ISSUE TITLE
el-select 下拉框在formgroup里面修改值之后，下拉框选项不更新

### ISSUE THREAD

**Issue by wmlzjb** [ElemeFE/element-angular#122]
Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

Version & Environment:  
Angular: 6.0.0
element-angular: 0.7.6

Description:
在form表单中给select绑定formControlName，然后this.form.get('goId').setValue('2'); 
下拉框的选项不会更新，但是值是发生了变化,如果在formgroup中给默认值，下拉框是可以默认选中的，只有setvalue是失效的

**Comment by WittBulter** [comment]
got it.
