### ISSUE TITLE
指定展开submenu

### ISSUE THREAD

**Issue by jasminecjc** [ElemeFE/element-angular#124]
Issue Type:
- [ ] Bug
- [x] Feature
- [ ] Help

Version & Environment:  

Description:
http://element.eleme.io/#/zh-CN/component/menu
elementui支持的功能，现在element-angular是否同步支持
![image](https://user-images.githubusercontent.com/13568376/41016273-e4701f6c-6980-11e8-86b3-2218da12f84c.png)

**Comment by WittBulter** [comment]
暂时还未同步 EL 的所有功能。
