### ISSUE TITLE
How to set step for el-slider

### ISSUE THREAD

**Issue by ft115637850** [ElemeFE/element-angular#126]
Issue Type:
- [ ] Bug
- [ ] Feature
- [X] Help

Description:
I want to set step for el-slider. How can I do this ?

**Comment by w-xuefeng** [comment]
you can use a function to bind to [format-tooltip], which will return an anonymous function with a 
parameter  to calculate your step.
like this:
```html
<el-slider [min]="1" [max]="9" [model]="data" [format-tooltip]="sliderFormat()"></el-slider>
```
```ts
  sliderFormat() {
    return function (val) {
      return (val * 10).toString();
    }
  }
```
This will achieve the ten-step with one slide.

**Comment by Tumiz** [comment]
It is a bug, element ui always take this property as a String, but only Number is accepted.
