### ISSUE TITLE
表单验证的错误提示如何手动触发

### ISSUE THREAD

**Issue by 85204** [ElemeFE/element-angular#133]
官网的表单验证需要手动填写表单来触发change事件才能实现错误提示，
但是字段未填写的错误提示在用户不填写表单直接提交的时候触发不了。
请问如何触发这个提示？
尝试用
window.dispatchEvent(new Event('onchange'))
之类的事件也没有反应
请问是不是我dispatch的事件名有问题还是什么？
在使用element官网的错误提示下，有什么更好的解决办法吗？

Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

**Comment by firstsir0** [comment]
我干过一个坑的，直接在那个值后面几个东西.....然后触发。太临时的解决办法了

**Comment by 85204** [comment]
> 我干过一个坑的，直接在那个值后面几个东西.....然后触发。太临时的解决办法了

已经解决了，代码参考antd相关部分即可
http://ng.ant.design/components/form/zh#components-form-demo-normal-login
