### ISSUE TITLE
django+angular element-upload

### ISSUE THREAD

**Issue by lfpython** [ElemeFE/element-angular#14]
Issue Type:
- [ ] Bug
- [ ] Feature
- [ ok] Help

Version & Environment:  
windows 10
angular 5.2.0

Description:
![image](https://user-images.githubusercontent.com/30587780/35804436-c127e468-0ab2-11e8-93a0-676170d7dfd6.png)
为什么我的图片不能上传啊，415状态码，django后台

**Comment by WittBulter** [comment]
注意错误：不支持的媒体类型。看起来是你的接口对上传文件的限制？

**Comment by stars21** [comment]
NavMenu 这个菜单要支持一下展开和关闭功能，请问什么时候可以开发这个功能呢？
现在紧切需要这个功能哈
什么时候开发好

**Comment by WittBulter** [comment]
@lfpython 时间太长先关闭了，有其他补充信息请重开 issue。
