### ISSUE TITLE
 element-angular  中tree 控件中有个UserSafeHooks  这个是什么  怎么用呀

### ISSUE THREAD

**Issue by zhaojinxiong** [ElemeFE/element-angular#15]
Issue Type:
- [x] Bug
- [ ] Feature
- [x] Help

Version & Environment:  
0.5.6

Description:
 element-angular  中tree 控件中有个UserSafeHooks  这个是什么  怎么用呀

**Comment by WittBulter** [comment]
`removeAllChecked` 等方法是 Tree 的实例方法，可以注入 Tree 或者直接选取这个元素使用，但实际上用户完全可以看到、修改更多的方法与属性，或是误改一些属性（如 assign 新的属性在实例中）。

所以需要使用实例的方法时，运行实例下的 `UserSafeHooks` ，它会返回几个向用户扩展开放的方法。简单的说这是一种隔离措施，虽然从严格的技术角度来说并无多大意义 （毕竟你想改某个属性我也不能拦着你是吧），但给用户传达了一种信息，由 `UserSafeHooks` 返回的方法是提供给用户的、可靠的、无副作用的。

**Comment by zhaojinxiong** [comment]
我不知道怎引入 这个 [ts] 找不到名称“UserSafeHooks”。

**Comment by WittBulter** [comment]
在示例文档的代码中已经有写：
```html
<el-tree [model]="data3" [show-checkbox]="true" #tree>
</el-tree>

<script>
// in Component:
@ViewChild('tree') tree: any

ngAfterViewInit(): void {
  if (!this.tree) return
  this.hooks = this.tree.userSafeHooks()
}
</script>
```

**Comment by zhaojinxiong** [comment]
就是找不到 UserSafeHooks  这个类型 作者大大

**Comment by WittBulter** [comment]
`UserSafeHooks` 类型在 `element-angular/release/tree` 下面，你可以看一下。
一般 IDE 会在你输入 `UserSafeHooks` 之后自动帮你 Import 好类型的.....😥

如果是提示 `tree` 找不到类型  `userSafeHooks` 错误，应该是你 `@ViewChild('tree') tree` 的类型标注错了，因为它不是标准的 `ElementRef`。你可以选择标注为 `@ViewChild('tree') tree: ElementRef & ElTree` 或者手动指定类型 `(<Tree>this.tree).userSafeHooks`。
当然你也可以偷个懒直接 any...😅

**Comment by zhaojinxiong** [comment]
不行啊 找不到 我 ng g c  compent   一个 然后想在html 写Eltree组件 组件能显示出来 就这个UserSafeHooks 出不来 按你说的方法还是不行

**Comment by WittBulter** [comment]
把你代码传到 github 或者在线编辑的网站吧，我给你 debug。

**Comment by zhaojinxiong** [comment]
https://github.com/zhaojinxiong/angular/tree/master/taskmag 好了大大~我是学生

**Comment by WittBulter** [comment]
`(<Tree>this.tree).userSafeHooks()` => `(<any>this.tree).userSafeHooks()`
你不熟就直接这样用吧

**Comment by sophialady** [comment]
你好，这个更新选中值updateItemChecked，只能选中一个吗？多选怎么设置
