### ISSUE TITLE
IE11 issue

### ISSUE THREAD

**Issue by Sancho66** [ElemeFE/element-angular#20]
Issue Type:
- [ ] Bug
On IE11 I have this errror :Can't resolve all parameters for ElTooltip: ([object Object], [object Object], ?). 

Version & Environment:  
Angular 5 , all polyfills installed , IE11 and chrome.
element-angular 0.5.7

Description:
Thanks for your recent update we are close to resolve IE compatibility.
When I load element-angular module on IE 11 I have errors belows :
`Can't resolve all parameters for ElTooltip: ([object Object], [object Object], ?).` and in more details
 
stack	`Error: Can't resolve all parameters for ElTooltip: ([object Object], [object Object], ?).\n   at CompileMetadataResolver.prototype._reportError (eval code:16196:13)\n   at CompileMetadataResolver.prototype._getDependenciesMetadata (eval code:15913:17)\n   at CompileMetadataResolver.prototype._getTypeMetadata (eval code:15746:9)\n   at CompileMetadataResolver.prototype.getNonNormalizedDirectiveMetadata (eval code:15228:9)\n   at CompileMetadataResolver.prototype._getEntryComponentMetadata (eval code:16061:9)\n   at Anonymous function (eval code:15531:40)\n   at CompileMetadataResolver.prototype.getNgModuleMetadata (eval code:15530:13)\n   at CompileMetadataResolver.prototype.getNgModuleSummary (eval code:15346:13)\n   at Anonymous function (eval code:15444:21)\n   at CompileMetadataResolver.prototype.getNgModuleMetadata (eval code:15422:13)`

and `access property "arguments" non authorized in strict mode`

Please can you help me ?

**Comment by WittBulter** [comment]
Emm... there's nothing I can do about it, element-angular export ES5 by default in version 0.6.0 .
😔

**Comment by Sancho66** [comment]
Still Does not work with 0.6.0 version or 0.6.1. :'( 
Element-angular is the only library which doesn't work on my project with IE throught all libraries I have installed.

I think the issue is in : 
`type	function ElTooltip(renderer, el, window) { this.renderer = renderer; this.el = el; this.window = window; this.elDisabled = false; this.watch = false; this.placement = 'bottom'; this.effect = 'dark'; this.visibleArrow = true; this.xPlacement = 'bottom'; this.showPopper = true; this.cache = {}; }`
