### ISSUE TITLE
<el-main> 标签上使用 ngIf ，当表达式从true变为false时无法正确删除元素

### ISSUE THREAD

**Issue by huazhu111** [ElemeFE/element-angular#23]
Issue Type:
- [ √] Bug

Version & Environment:  
elementUI 0.5.7
angular 5.2.4

Description:
渲染时ngIf的表达式为false时正确渲染（不渲染）
当ngIf的表达式从true变为false时，元素不会消失
只在<el-main>上试了，暂时还不知道其他标签有没有这个问题
现在只能在外面再套一层 \<div\> 来放ngIf

PS：谢谢维特这么快就把折叠菜单的BUG修了，摸摸哒

**Comment by WittBulter** [comment]
这是一个设计上的错误，NG 的组件打包方式会阻止外部的样式影响组件本身 (作为第三方库必须要选择这种打包方式，否则样式会污染其他组件)，对于 Container 组件来说，组件上继承的样式不能正确的作用于组件内部，特别是伪类、选择相邻元素时。所以这个组件在设计之初为了保证内部样式不受影响同时继承用户的自定义 class 而移除了 Angular 本身的 TAG (同时也移除了双向绑定)。

这种做法不符合 Angular 组件本身的设计思想，这样做的目的是更贴近 Vue 版本的 Element UI 风格，吸引原有的 Element UI 用户，如今看来这是一个不合理的设计。后面我新增了 Container 指令来代替组件，组件在下下个版本会被移除。

所以目前使用 Container 组件的地方需要手动替换成指令，接口没有变化，文档已经更新。为升级对大家造成的影响感到抱歉。
(还有极少数地方仍旧采用了移除 NG TAG 的设计方式，在未来可能发生微小的变化，但目前看来对用户影响不大)
