### ISSUE TITLE
Website English version not all in English

### ISSUE THREAD

**Issue by xxis** [ElemeFE/element-angular#34]
Issue Type:
- [ X] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  
Documentation Website: https://element-angular.faas.ele.me/guide/install

Description:
the website even when in English does not translate much of the page.

![element angular ex](https://user-images.githubusercontent.com/6135868/36280704-0fab7dee-12eb-11e8-9675-77bddca1b04c.png)

the Vue version of the documentation does not have issues, and i understand i can use that for the time being, however i plan to use this for an enterprise application and having the documentation page in a non-English page will be a difficult sell. which is a shame as this is a very complete and amazing library.

**Comment by WittBulter** [comment]
thanks for your issue, this is a key problem as this repo. 
to solve this problem, i developed an extra desktop application, but the translation work is a bit hard for me, this is the cause of slow progress. 

i plan to work on translation in the next few weeks, of course, if a contributor wants to participate in the translation work, I would like to welcome it very much (email: nanazuimeng123@gmail.com).

(we are working to solve this problem. don't worry.)
<img width="797" alt="fission" src="https://user-images.githubusercontent.com/11304944/36340300-f80fb8a0-1414-11e8-825e-32f71a497c00.png">
