### ISSUE TITLE
el-menu-item 绑定click 和 routerLink 进行跳转的时候没有效果

### ISSUE THREAD

**Issue by zhaoshiming** [ElemeFE/element-angular#4]
Issue Type:
- [ ] Bug

Version & Environment:  

"@angular/cli": "1.6.5",
    "@angular/core": "^5.2.0",
    "element-angular": "^0.5.4",

Description:
我在这个元素上绑定routerLink="/index"的时候是无效的，换成（click)="go()"也是无效的，并且在对应的元素上没有看到（click）绑定在元素上。 
另外el-for-angular是不是没有 :router这个属性，因为我这样尝试的时候也是无效的。
谢谢。

**Comment by WittBulter** [comment]
没有 `:router` 属性，因为把整个 router 对象传递太大了不合适。
你可以把 model 分开绑定为 `(modelChange)="go($event)"` 来拿到当前的点击的子菜单的值。menu-item 本身是没有点击事件的。

另外集成路由用 `router-link` 绑定也不错，后续可以在 `menu-item` 加上这个属性。

**Comment by WittBulter** [comment]
#7 ，已经加上了。
