### ISSUE TITLE
在form中Switch，Radio 的问题

### ISSUE THREAD

**Issue by Cyclone77** [ElemeFE/element-angular#40]
Issue Type:
- [x] Bug

Version & Environment:  

1. 在form中Switch虽然设置值没有问题，但是按钮没切换，如图：

![switch](https://user-images.githubusercontent.com/10395760/36776999-b428fb24-1ca2-11e8-8392-06ada43ac596.png)

图中可以看出设置的是true，按钮应该在右边。

2. Radio初始化的时候设置值或者更新（用validateForm.patchValue()）无法设置值。
Description:

**Comment by WittBulter** [comment]
问题 2 已修复。
1 不能重现， patchValue 时 Switch 组件能够正确的移动，你检查一下自己的代码，如果问题还是存在，需要你提供更多代码与示例。
