### ISSUE TITLE
ERROR Error: Found the synthetic property @dropAnimation. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

### ISSUE THREAD

**Issue by Kanchil** [ElemeFE/element-angular#46]
Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

Version & Environment:  
node 8.4
windows 10
谷歌浏览器

Description:

![1](https://user-images.githubusercontent.com/20110220/37141162-24be0666-22ef-11e8-9536-84e1c697148b.png)

1.在header.componet.html中引入el-menu组件
![2](https://user-images.githubusercontent.com/20110220/37141579-6aa97d8a-22f0-11e8-9cbf-e57dd3ab473c.png)

2.在shared.module.ts中引入ElModule，并且导出
![3](https://user-images.githubusercontent.com/20110220/37141584-72461d0a-22f0-11e8-8ee1-0c7855a02af3.png)

3.然后在app.module.ts再引入shared.module。报的这个错误
![4](https://user-images.githubusercontent.com/20110220/37141591-79a2edd0-22f0-11e8-9eb2-4609579556ef.png)

**Comment by WittBulter** [comment]
这个组件用到了 Angular 的动画模块，需要你在 `app.module.ts` 中添加这个模块：
```typescript
//...
imports: [
  CommonModule,
  BrowserAnimationsModule,
  ElModule.forRoot()
],
```

添加 `BrowserAnimationsModule` 即可，如果不想引入动画模块，使用 `NoopAnimationsModule` 代替则会取消所有动画。

**Comment by Kanchil** [comment]
谢谢大佬的回答！问题已解决！
我在app.module.ts中引入ElModule，在header.component.html引入el-menu组件，报template parse error!
