### ISSUE TITLE
el-table 组件设置 center="all"； 表格头不能正常居中显示

### ISSUE THREAD

**Issue by Kanchil** [ElemeFE/element-angular#47]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  

Description:
el-table 组件设置 center="all"；如果el-table-column组件设置width属性为某一值时，表格头可以正常居中显示；如果不设置width，让这一列自适应宽度时这一列的表格头不能居中显示，表格中其它行却是正常居中的！

**Comment by WittBulter** [comment]
需要补充你的代码。

**Comment by Kanchil** [comment]
![1](https://user-images.githubusercontent.com/20110220/37188590-f42fab3e-238a-11e8-9be2-7cead5b57b0c.png)
![2](https://user-images.githubusercontent.com/20110220/37188593-f7b4f48a-238a-11e8-8052-b18eb43dff68.png)
