### ISSUE TITLE
component i18n

### ISSUE THREAD

**Issue by yinjs** [ElemeFE/element-angular#48]
Issue Type:
- [x] Bug
- [x] Feature
- [ ] Help

Version & Environment:  
0.6.3

Description:
i18n for components are missing
e.g. pagination component have some Chinese characters hard-coded and we need abstract all these to configurable like vue version did. (please refer http://element.eleme.io/#/zh-CN/component/i18n)

**Comment by WittBulter** [comment]
#34

**Comment by yinjs** [comment]
@WittBulter it's not the same thing. Could you have a look at my issue description :(

**Comment by yinjs** [comment]
@WittBulter I'm using angular element to develop web app for English user. Component like Paignation shows Chinese characters

**Comment by WittBulter** [comment]
it's also in the plan.
