### ISSUE TITLE
能不能写一点demo 啊，大神。你的东西虽好但是不知道怎么用啊。布局怎么写啊

### ISSUE THREAD

**Issue by 5nn** [ElemeFE/element-angular#5]
Issue Type:
- [ ] Bug
- [x] Feature
- [ ] Help

Version & Environment:  

Description:

**Comment by 5nn** [comment]
特性

**Comment by WittBulter** [comment]
计划于近期写一个使用 Element Angular 搭建的企业级后台，供作参考。目前还是要参考文档来开发。

**Comment by stars21** [comment]
NavMenu 这个菜单要支持一下展开和关闭功能，请问什么时候可以开发这个功能呢？
现在紧切需要这个功能哈
什么时候开发好
