### ISSUE TITLE
el-table-column > ng-template中*ngIf部分情况不生效

### ISSUE THREAD

**Issue by yinjs** [ElemeFE/element-angular#50]
Issue Type:
- [ ] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  
0.6.3

Description:
el-table-column > ng-template中*ngIf如果引用了之前column中没出现过的model key总是判断为*ngIf="false"

以下例子中的Block/Unblock button无法正常切换

<el-table class="app-list-content-table" *ngIf="companyList" [model]="companyList.elements">
    <el-table-column width="55">
      <ng-template #slot let-scope="scope">
        <el-checkbox [model]="selection[scope.rowData.id]" (modelChange)="handleRowSelection($event, scope.rowData.id)"></el-checkbox>
      </ng-template>
    </el-table-column>
    <el-table-column model-key="id" label="ID" width="300"></el-table-column>
    <el-table-column model-key="name" label="Name" width="250"></el-table-column>
    
    
    <el-table-column label="Actions" width="120">
      <ng-template #slot let-scope="scope">
        <el-button type="text" size="small">
          <a [routerLink]="['/companies', scope.rowData.id]" routerLinkActive="active">View</a>
        </el-button>
        <el-button type="text" size="small" *ngIf="scope.rowData?.blocked" (click)="setBlock(scope.rowData.id, false)">Unblock</el-button>
        <el-button type="text" size="small" *ngIf="!scope.rowData?.blocked" (click)="setBlock(scope.rowData.blocked, true)">Block</el-button>
      </ng-template>
    </el-table-column>
  </el-table>

**Comment by WittBulter** [comment]
你这里的代码标签都没有闭合，应该是不能正常工作的。另外请用代码格式贴上代码。

**Comment by yinjs** [comment]
`<el-table class="app-list-content-table" *ngIf="companyList" [model]="companyList.elements">
    <el-table-column model-key="id" label="ID" width="300"></el-table-column>
    <el-table-column model-key="name" label="Name" width="250"></el-table-column>
    <el-table-column label="Actions" width="120">
      <ng-template #slot let-scope="scope">
        <el-button type="text" size="small">
          <a [routerLink]="['/companies', scope.rowData.id]" routerLinkActive="active">View</a>
        </el-button>
        <el-button type="text" size="small" *ngIf="scope.rowData?.blocked" (click)="setBlock(scope.rowData.id, false)">Unblock</el-button>
        <el-button type="text" size="small" *ngIf="!scope.rowData?.blocked" (click)="setBlock(scope.rowData.blocked, true)">Block</el-button>
      </ng-template>
    </el-table-column>
  </el-table>`

**Comment by yinjs** [comment]
如果在ｔａｂｌｅ　ｃｏｌｕｍｎ中加一列ｂｌｏｃｋ先把值读出来是有ｔｒｕｅ／ｆａｌｓｅ的，最后一列中的ｎｇｉｆ也能正常了，但是我不想要显式的出来ｂｌｏｃｋ列，只是希望在最后一列ａｃｔｉｏｎｓ中根据ｂｌｏｃｋｅｄ的值切换ｂｕｔｔｏｎ

**Comment by WittBulter** [comment]
请注意组织好语言、代码格式等，问题不可读我也不知道你想说什么。
这个 issue 先关闭了，如果你准备好了相关信息请重开一个 issue。
谢谢你的关注。
