### ISSUE TITLE
ngIf is not working in table column

### ISSUE THREAD

**Issue by yinjs** [ElemeFE/element-angular#52]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  
0.6.3

Description:
ngIf is not working in table column

Please refer the shared code for more details. In the data model one row is blocked and another is not. But in table view they are both unblocked(bocked: false/undefined)

[https://stackblitz.com/edit/angular-ed49je](https://stackblitz.com/edit/angular-ed49je)

**Comment by WittBulter** [comment]
append `<el-table-column model-key="blocked" label="blocked"  width="100"></el-table-column>` to table element can resolve this issue, but it's a not good way. look like binding strategy error.

i will fix it in next days.

**Comment by WittBulter** [comment]
fixed, upgrade to `v0.6.4` .
