### ISSUE TITLE
form become invalid even all controls validation pass

### ISSUE THREAD

**Issue by yinjs** [ElemeFE/element-angular#56]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  
0.6.4

Description:
Form become invalid even all controls validation pass. This may caused by element-angular returns { status: "success"} when validation pass to flag the field to green. But angular treated this as an error. 

As a workaround we may ignore the angular native formGroup.valid state and check if all control.errors contains { status: "success"}

Below is code to reproduce this issue
[https://stackblitz.com/edit/angular-pibr2u](https://stackblitz.com/edit/angular-pibr2u)

**Comment by WittBulter** [comment]
this is a known issue. 
the advantage of doing this is that it's more simple, but it affects the value of the `valid`, if your want use `valid`, please refer:
```typescript
emailValidator(): (control: FormControl) {
  // error ....

  // success
  return {}
}
```
