### ISSUE TITLE
el-checkbox get null parent when it's inside content projection

### ISSUE THREAD

**Issue by yinjs** [ElemeFE/element-angular#57]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  
0.6.4

Description:
el-checkbox get null parent when it's inside content projection. This only happens when using <ng-content select="xxx"></ng-content> with "select" directive.

Code to reproduce (check browser console for the error)

[https://stackblitz.com/edit/angular-p7gezx?file=app%2Fapp.component.html](https://stackblitz.com/edit/angular-p7gezx?file=app%2Fapp.component.html)

**Comment by WittBulter** [comment]
this style is not supported at the moment.

**Comment by yinjs** [comment]
@WittBulter as a workaround I use an el-form to wrap the content
