### ISSUE TITLE
el-table  how to re-render the table when data changed

### ISSUE THREAD

**Issue by fangdingjun** [ElemeFE/element-angular#65]
Issue Type:
- [ ] Bug
- [ ] Feature
- [* ] Help

Version & Environment:  
0.6.5

Description:
`<el-table [model]="data">
<el-table-column label="xx">....
</el-table>`

when the model data changed, how to refresh the table display?

I try to use el-table and el-pagination display some data, but I can not update the table content when page changed, please help.

**Comment by WittBulter** [comment]
looks like table component response issue, but its work normal on my project, can you post more codes or [online example](https://stackblitz.com/) ?

**Comment by fangdingjun** [comment]
I post my code here, please help me to see something wrong, thanks.
https://stackblitz.com/edit/angular-2amuff

**Comment by WittBulter** [comment]
fixed, upgrade to v0.6.7.
