### ISSUE TITLE
el-dialog 回调函数before-close方法中怎么调用原来的Component而不是dialog.

### ISSUE THREAD

**Issue by gaomingen** [ElemeFE/element-angular#67]
Issue Type:
- [ ] Bug
- [ ] Feature
- [ 1] Help

Version & Environment:  

0.6.3

Description:
回调函数before-close方法中 this 关键字不是原来的Component 而是dialog的.

**Comment by WittBulter** [comment]
如果要绑定 Component 的直接使用 `[before-close]="handle.bind(this)"`
