### ISSUE TITLE
The back end of the file upload component can't find "file"

### ISSUE THREAD

**Issue by leihg** [ElemeFE/element-angular#68]
Issue Type:
- [ ] Help

Version & Environment:  

Description:
The back end of the file upload component can't find "file"

**Comment by WittBulter** [comment]
i need more information with element-angular console message, and your code.
if you still have a issue, open a new issue.

**Comment by leihg** [comment]
![image](https://user-images.githubusercontent.com/19809782/38237056-a10b3a4a-3758-11e8-958f-a75d8dbbb379.png)
