### ISSUE TITLE
tree

### ISSUE THREAD

**Issue by shiyuanping** [ElemeFE/element-angular#71]
Issue Type:
- [ ] Bug

Version & Environment:  

0.6.4

Description:
在使用[expand-on-click-node] = "false"（不允许点击非图标区域触发展开收起动作）想要实现只点击图标展开收起，而不是点击文字展开收起。但是使用完之后发现，modelChange点击响应事件不能用了，只有点击那个向下的图标函数才有响应

**Comment by shiyuanping** [comment]
Witt, 想问下我提的这个问题解决了嘛?

**Comment by WittBulter** [comment]
@shiyuanping 已经解决了，但是还没有发新版本。

**Comment by WittBulter** [comment]
released v0.7.1, #74

**Comment by shiyuanping** [comment]
新版本什么时候发布呢

**Comment by WittBulter** [comment]
@shiyuanping 

> released v0.7.1, #74

**Comment by shiyuanping** [comment]
ok! 测试了一下，可以用了^_^

**Comment by shiyuanping** [comment]
@WittBulter  之前使用了0.7.1的版本，可以用。然后今天项目测试的时候，同样的问题又出现了，modelchange点击事件还是没有反应
