### ISSUE TITLE
按项目主页的说明引入单个组件 失败。

### ISSUE THREAD

**Issue by wgf4242** [ElemeFE/element-angular#77]
Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

Version & Environment:  
ng 5.

Description:

Unexpected value 'undefined' imported by the module 'AppModule'

https://stackblitz.com/edit/angular-el-angular-test
```
# app.module.ts
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    BrowserAnimationsModule,
    ElChildModules.ElDataPicker
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

[Solved] Thanks to WittBulter
`
imports:[
    ElChildModules.ElInputsModule.forRoot(),
    ElChildModules.ElDateModule.forRoot()
]
`

**Comment by WittBulter** [comment]
this issue maybe a typo: `ElDataPicker` => `ElDateModule`.

All submodules please see [here](https://github.com/ElemeFE/element-angular/blob/master/src/element-angular.module.ts#L43)

**Comment by wgf4242** [comment]
I use     ElChildModules.ElDateModule or ElChildModules.ElDateModule.forRoot(), then get another error .
preview-e0903b47b015eda0b7ee.js:1 ERROR Error: StaticInjectorError(AppModule)[ElInput -> ElFormItem]: 
  StaticInjectorError(Platform: core)[ElInput -> ElFormItem]: 

https://stackblitz.com/edit/angular-el-angular-test

**Comment by WittBulter** [comment]
apparent, date component depend on input component.
