### ISSUE TITLE
无法找到 ExAppComponent

### ISSUE THREAD

**Issue by lifeipt** [ElemeFE/element-angular#8]
Issue Type:
- [ ] Bug
- [ ] Feature
- [1 ] Help

Version & Environment:  

Description:
根目录，app.module.ts引入
declarations: [
    ExAppComponent,
],
这个ExAppComponent是哪里来的呢？

提示can't find name 'ExAppComponent'

**Comment by WittBulter** [comment]
`ExAppComponent` 是我演示举得例子，如果在你自己的项目里就是普通的 AppComponent，意思就是入口的 Component，这不是组件的一部分，而是示例。
