### ISSUE TITLE
怎么处理表单验证？

### ISSUE THREAD

**Issue by scgy5555** [ElemeFE/element-angular#90]
Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

Version & Environment:  
0.7.0

Description:
组件文档里的form表单不能触发invalid状态变化，应该怎么做表单验证的处理？用什么值进行判断是否通过验证？

**Comment by WittBulter** [comment]
你可以看一下 NG 的响应式表单文档，同时也看一下 Element Angular 文档。
这里没有触发 valid 的状态是因为示例中的 validator 返回了一个对象引起的，你可以跟着官方的来或者用Element Angular 示例中的 `statusCtrl` 方法来验证。具体如何取舍看你的抽象方式了。

**Comment by scgy5555** [comment]
是的，我看到了它返回了一个对象，如果用statusCtrl的方式，是不是就不能使用FormItem组件的验证消息了

**Comment by gaomingen** [comment]
监听form表单值得变化 ;

   valid = false ;   //对应validateForm.valid  false默认验证失败
    this.validateForm.valueChanges.subscribe((res) => {
      this.valid = true;
      A:for (const key  in this.validateForm.controls) {
        const item = this.validateForm.controls;  
        //验证有异常时不通过验证
        if (item[key].errors && item[key].errors.status && item[key].errors.status === 'error') {
          this.valid = false;
          break A;
              }
         }
    });

**Comment by WittBulter** [comment]
@gaomingen 👍
