### ISSUE TITLE
折叠面板默认展开模式

### ISSUE THREAD

**Issue by jasminecjc** [ElemeFE/element-angular#91]
Issue Type:
- [ ] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  

Description:
建议增加折叠面板默认展开/折叠模式开关控制

**Comment by WittBulter** [comment]
为折叠面板的 `model` 增加了展开状态的追踪功能，提供初始的 `model` 值即可展开指定项。
在这之前 `model` 的初始值意义也不明，现在能够提供一个比较好的功能。(还未发布新版本)
